---
- name: "upper.io deployment playbook"
  hosts: "*"
  tasks:
    - name: "create shared network"
      docker_network:
        name: "{{ network_name }}"
        state: "present"
    - import_tasks: pgserver/tasks.yml
    - import_tasks: playground-executor/tasks.yml
    - import_tasks: playground-webapp/tasks.yml
    - import_tasks: tour/tasks.yml
    - import_tasks: site/tasks.yml
    - import_tasks: vanity/tasks.yml
    - import_tasks: nginx/tasks.yml
