- hosts: "all"
  tasks:
    - name: "push requirements"
      copy:
        src: "./requirements.txt"
        dest: "{{ services_base_dir }}/requirements.txt"
    - name: "install requirements and create virtualenv"
      pip:
        requirements: "{{ services_base_dir }}/requirements.txt"
        virtualenv: "{{ virtualenv_dir }}"
        virtualenv_command: "python3 -m venv"
    - name: "set ansible_python_interpreter"
      set_fact:
        ansible_python_interpreter: "{{ virtualenv_dir }}/bin/python3"

- hosts: "all"
  tasks:
    - name: "create shared network"
      docker_network:
        name: "{{ network_name }}"
        driver: "bridge"
        state: "present"
      run_once: true

- hosts: "pgserver"
  tasks:
    - import_tasks: pgserver/ansible/tasks.yml

- hosts: "playground_executor"
  tasks:
    - import_tasks: playground-executor/ansible/tasks.yml

- hosts: "playground_webapp"
  tasks:
    - import_tasks: playground-webapp/ansible/tasks.yml

- hosts: "tour"
  tasks:
    - import_tasks: tour/ansible/tasks.yml

- hosts: "site"
  tasks:
    - import_tasks: site/ansible/tasks.yml

- hosts: "vanity"
  tasks:
    - import_tasks: vanity/ansible/tasks.yml

- hosts: "nginx"
  tasks:
    - import_tasks: nginx/ansible/tasks.yml
