dev:
  vars:
    ansible_host: "dev.oslab.hub"
  hosts:
    pgserver:
    playground_executor:
    playground_webapp:
    tour:
    site:
    vanity:
    nginx:
      container_bind_ip: "10.0.28.80"
      container_bind_port: "2645"
