- set_fact:
    image_name: "upper/site"
    image_tag: "{{ docker_image_tag }}"
    container_name: "upper-site"
- set_fact:
    image_full_name: "{{ image_name }}:{{ image_tag }}"
- name: "pull docker image: {{ image_full_name }}"
  docker_image:
    name: "{{ image_full_name }}"
    source: "pull"
    state: "present"
- name: "stop container: {{ container_name }}"
  docker_container:
    name: "{{ container_name }}"
    state: "stopped"
  ignore_errors: "yes"
- name: "(re)start container: {{ container_name }}"
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_full_name }}"
    state: "started"
    restart_policy: "always"
    networks:
      - name: "{{ network_name }}"
    ports:
      - "{{ container_bind_ip }}:8080:80"
    env:
      ENV: "{{ env }}"
